import {expect, test} from '@playwright/test'
import {readFile} from 'node:fs/promises'

test.beforeEach(async ({page}) => {
  await page.addInitScript(() => {localStorage.setItem('azurpilot.theme', 'light'); localStorage.setItem('azurpilot.language', 'zh-CN')})
})
async function choose(page: import('@playwright/test').Page, label: string, option: string) {
  await page.getByRole('combobox', {name: label, exact: true}).click()
  await page.getByRole('option', {name: option, exact: true}).click()
}
test('独立资源页完成图表、归因筛选、分页、导出和控制设置保存', async ({page}) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/#/i/demo-main/resources')
  await expect(page.getByRole('heading', {name: '资源管理', exact: true})).toBeVisible()
  await expect(page.getByRole('img', {name: '资源流向', exact: true})).toBeVisible()
  await expect(page.locator('.resource-sankey svg path').first()).toBeVisible()
  await expect(page.locator('.resource-evidence.adjustment')).toHaveText('待归因变化')
  const inventory = page.locator('.resource-panel').filter({has: page.getByRole('heading', {name: '资源总览'})})
  const oil = inventory.getByRole('row').filter({has: page.getByRole('button', {name: '石油', exact: true})})
  await expect(oil).toContainText('1,800')
  await expect(oil).toContainText('1,650')
  await choose(page, '任务', '委托')
  await expect(page.getByText('共 1 条', {exact: true})).toBeVisible()
  await expect(page.locator('.resource-evidence')).toHaveText('奖励识别')
  await choose(page, '任务', '所有任务')
  await choose(page, '资源', '所有资源')
  await expect(page.getByText('共 149 条', {exact: true})).toBeVisible()
  await page.getByRole('button', {name: '下一页', exact: true}).click()
  await expect(page.locator('.resource-panel').filter({has: page.getByRole('heading', {name: '收支明细'})}).getByRole('row')).toHaveCount(50)
  const download = page.waitForEvent('download')
  await page.getByRole('button', {name: '导出全部筛选明细', exact: true}).click()
  const csv = await readFile((await (await download).path())!, 'utf8')
  expect(csv.trim().split('\r\n')).toHaveLength(150)
  expect(csv).toContain('后宅购粮')
  expect(csv).toContain('待归因变化')
  await page.getByLabel('控制线', {exact: true}).fill('23000')
  await page.getByRole('checkbox', {name: '启用自动清油', exact: true}).uncheck()
  await page.getByRole('button', {name: '保存控制设置', exact: true}).click()
  await expect(page.getByRole('status').filter({hasText: '已保存'})).toBeVisible()
  await page.reload()
  await expect(page.getByLabel('控制线', {exact: true})).toHaveValue('23000')
  await expect(page.getByRole('checkbox', {name: '启用自动清油', exact: true})).not.toBeChecked()
  await choose(page, '资源', '所有资源')
  await page.screenshot({path: test.info().outputPath('resource-management.png'), fullPage: true})
  expect(errors).toEqual([])
})
test('空实例不伪造收支与库存，窄屏保持可操作且日期错误可恢复', async ({page}) => {
  await page.setViewportSize({width: 430, height: 900})
  await page.goto('/#/i/demo-alt/resources')
  await expect(page.getByText('此区间尚无收支记录').first()).toBeVisible()
  await expect(page.getByRole('button', {name: '导出全部筛选明细', exact: true})).toBeDisabled()
  await expect(page.locator('.resource-sankey')).toHaveCount(0)
  await choose(page, '时间范围', '自定义')
  await page.getByLabel('开始时间', {exact: true}).fill('2026-10-08T12:00')
  await page.getByLabel('结束时间', {exact: true}).fill('2026-10-07T12:00')
  await page.getByRole('button', {name: '应用区间', exact: true}).click()
  await expect(page.getByRole('alert')).toContainText('请选择不超过一年的有效本地时间区间')
  await choose(page, '时间范围', '最近 7 天')
  await expect(page.getByRole('alert')).toHaveCount(0)
  await page.screenshot({path: test.info().outputPath('resources-mobile-empty.png'), fullPage: true})
  const width = await page.evaluate(() => ({body: document.documentElement.scrollWidth, viewport: innerWidth}))
  expect(width.body).toBeLessThanOrEqual(width.viewport + 1)
})

test('窄屏有收支时展示实际数量并可从桑基图筛选任务', async ({page}) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.setViewportSize({width: 430, height: 900})
  await page.goto('/#/i/demo-main/resources')
  const graph = page.locator('.resource-sankey')
  await expect(graph.locator('svg')).toBeVisible()
  await expect(graph).toContainText('1,800')
  await graph.locator('text').filter({hasText: /^活动图-1$/}).click()
  await expect(page.getByText('共 1 条', {exact: true})).toBeVisible()
  await expect(page.locator('.resource-panel').filter({has: page.getByRole('heading', {name: '收支明细'})})).toContainText('活动图-1')
  await page.screenshot({path: test.info().outputPath('resources-mobile-flow.png'), fullPage: true})
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  expect(errors).toEqual([])
})
