import {expect,test} from '@playwright/test'
import {completeCaptcha} from './recaptcha'

test('金融图表、股票详情、全屏与平移、杠杆交易、验证码及永久实例绑定',async({page})=>{
  test.setTimeout(90000)
  const errors:string[]=[],responses:string[]=[],stockIds=new Set<string>()
  // 暂缓官方脚本加载，先确认未取得验证码 token 时无法提交注册。
  let startCaptcha!:()=>void
  const captchaReady=new Promise<void>(resolve=>{startCaptcha=resolve})
  await page.route('https://www.recaptcha.net/recaptcha/api.js**',async route=>{await captchaReady;await route.continue()})
  // 分别停在实例状态与行情加载阶段，确认始终可以返回总览。
  let releaseStatus!:()=>void,releaseMarket!:()=>void
  const statusReady=new Promise<void>(resolve=>{releaseStatus=resolve}),marketReady=new Promise<void>(resolve=>{releaseMarket=resolve})
  await page.routeWebSocket('**/api/v1/ws',socket=>{
    const server=socket.connectToServer(),requests=new Map<string,{method:string;params?:{path?:string}}>()
    socket.onMessage(message=>{const request=JSON.parse(String(message));if(request.id)requests.set(request.id,request);server.send(message)})
    server.onMessage(async message=>{
      const response=JSON.parse(String(message)),request=requests.get(response.id)
      if(request?.method==='stock.status')await statusReady
      if(request?.method==='stock.request'&&request.params?.path==='/market')await marketReady
      socket.send(message)
    })
  })
  page.on('pageerror',e=>errors.push(e.message))
  page.on('websocket',socket=>{
    socket.on('framesent',frame=>{const data=JSON.parse(String(frame.payload));if(data.method==='stock.request')stockIds.add(data.id)})
    socket.on('framereceived',frame=>{const raw=String(frame.payload),data=JSON.parse(raw);if(stockIds.has(data.id))responses.push(raw)})
  })
  await page.emulateMedia({reducedMotion:'reduce'})
  await page.addInitScript(()=>localStorage.setItem('azurpilot.theme','light'))
  await page.goto('/#/i/demo-main/overview')
  const enter=page.locator('.primary-nav').getByRole('link',{name:'茗喵证券交易所',exact:true}),settings=page.getByRole('button',{name:'仪表盘设置',exact:true})
  await expect(enter).toBeVisible();await expect(settings).toBeVisible();await expect(page.locator('.primary-nav a')).toHaveText(['运行总览','资源统计','茗喵证券交易所'])
  await expect(page.getByRole('link',{name:'进入茗喵证券交易所',exact:true})).toHaveCount(0);await expect(page.locator('.overview-page a[href$="/stock-exchange"]')).toHaveCount(0)
  await page.screenshot({path:'test-results/native-exchange-entry-desktop.png',fullPage:true})
  await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'打开导航',exact:true}).click();await expect(enter).toBeVisible()
  await page.screenshot({path:'test-results/native-exchange-entry-mobile.png',fullPage:true})
  await enter.click();const terminal=page.locator('.stock-terminal'),dialog=terminal.getByRole('dialog',{name:'开通交易账户'})
  await expect(page.locator('.stock-exchange-loading')).toBeVisible();await expect(page.getByRole('link',{name:'返回总览',exact:true})).toBeVisible()
  releaseStatus();await expect(terminal.getByText('正在连接交易终端…',{exact:true})).toBeVisible();await expect(terminal.getByRole('link',{name:'返回总览',exact:true})).toBeVisible()
  releaseMarket()
  await expect(dialog).toBeVisible()
  await page.setViewportSize({width:1600,height:1080})
  await expect(page.locator('.app-shell')).toHaveCount(0)
  await expect(terminal.getByRole('button',{name:'退出账户'})).toHaveCount(0)
  const back=terminal.locator('.mmex-topbar').getByRole('link',{name:'返回总览',exact:true})
  await dialog.getByRole('link',{name:'返回总览',exact:true}).click();await expect(page).toHaveURL(/#\/i\/demo-main\/overview$/);await expect(settings).toBeVisible();await expect(page.locator('.app-shell')).not.toHaveClass(/mobile-open/)
  await enter.click();await expect(dialog).toBeVisible();await dialog.getByRole('button',{name:'已有账户登录'}).click()
  const login=terminal.getByRole('dialog',{name:'登录交易账户'})
  await login.getByRole('link',{name:'返回总览',exact:true}).click();await expect(page).toHaveURL(/#\/i\/demo-main\/overview$/)
  await enter.click();await expect(dialog).toBeVisible()
  await expect(dialog.getByLabel('总行动力 · 初始股票报价')).toHaveCount(0)
  const username=`原生玩家${Date.now()}`
  await dialog.getByLabel('唯一用户名').fill(username);await dialog.getByLabel('密码',{exact:true}).fill('strong-test-password')
  await dialog.getByLabel('我已阅读注意事项').check();await expect(dialog.getByRole('button',{name:'验证并开通交易账户'})).toBeDisabled()
  startCaptcha();await completeCaptcha(page);await assertCaptchaCentered(page);await page.screenshot({path:'test-results/native-captcha-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});await assertCaptchaCentered(page);await page.screenshot({path:'test-results/native-captcha-mobile.png',fullPage:true});await page.setViewportSize({width:1600,height:1080});await expect(dialog.getByRole('button',{name:'验证并开通交易账户'})).toBeEnabled();await dialog.getByRole('button',{name:'验证并开通交易账户'}).click();await expect(dialog).not.toBeVisible({timeout:20000})
  await expect(terminal.getByRole('heading',{name:'每一份行动力，都有价值。'})).toBeVisible()
  await expect(terminal.locator('.mmex-breadcrumb,.mmex-topbar .connection')).toHaveCount(0)
  await expect(terminal.getByRole('button',{name:'刷新行情'})).toHaveCount(0)
  for(const width of [1600,1200,900,780,390]){
    await page.setViewportSize({width,height:844});await assertTopbarPinned(page)
  }
  await page.setViewportSize({width:1600,height:1080})
  await terminal.getByRole('button',{name:'查看我的身份识别码'}).click();const identityCard=terminal.getByRole('dialog',{name:'我的身份识别码'})
  await expect(identityCard).toContainText('仅你本人和管理员可查看');const identityCode=await identityCard.locator('code').textContent();expect(identityCode).toMatch(/^MMEX-(?:[A-F0-9]{8}-){3}[A-F0-9]{8}$/)
  await page.screenshot({path:'test-results/native-identity-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();await page.screenshot({path:'test-results/native-identity-mobile.png',fullPage:true});await identityCard.getByRole('button',{name:'关闭身份信息'}).click();await page.setViewportSize({width:1600,height:1080})
  const publicMarket=await (await page.request.get('http://127.0.0.1:8088/api/market')).text();expect(publicMarket).not.toContain('identityCode');expect(publicMarket).not.toContain(identityCode!)
  const desktop=await page.locator('.stock-exchange-shell').boundingBox();expect(desktop).toMatchObject({x:0,y:0,width:1600,height:1080})
  await expect(terminal.getByRole('button',{name:'行动力同步',exact:true})).toHaveCount(0);await expect(terminal.getByRole('link',{name:'交易所控制台'})).toHaveCount(0)
  await expect(terminal.locator('.mmex-sidebar nav button')).toHaveCount(5)
  await terminal.locator('.stock-row').filter({hasText:'MM000001'}).click()
  const initialMarket=await (await page.request.get('http://127.0.0.1:8088/api/market')).json(),initialStock=initialMarket.stocks.find((s:{id:number})=>s.id===1)
  const openingChange=initialStock.open>0?`${initialStock.quote.price>=initialStock.open?'+':''}${((initialStock.quote.price-initialStock.open)/initialStock.open*100).toFixed(2)}%`:'—'
  await expect(terminal.locator('.quote-price')).toContainText(openingChange);await expect(terminal.locator('.quote-price')).toContainText('较今日开盘')
  await expect(terminal.locator('.stock-row').filter({hasText:'MM000001'})).toContainText(openingChange)
  await expect(terminal.locator('.market-ticker button').filter({hasText:'MM000001'})).toContainText(openingChange)
  await terminal.getByRole('button',{name:'查看证券详情'}).click()
  await expect(terminal.locator('.stock-detail-page')).toBeVisible()
  await expect(terminal.locator('.stock-detail-price')).toContainText(openingChange);await expect(terminal.locator('.stock-detail-price')).toContainText('较今日开盘')
  await expect(terminal.locator('.execution-panel tbody tr')).not.toHaveCount(0)
  const financial=terminal.locator('.financial-chart'),range=financial.getByLabel('图表可视范围')
  for(const period of ['日K','M5','M10','M20','M30','M60','分时']){
    await financial.getByRole('button',{name:period,exact:true}).click()
    await expect(financial.locator('.financial-chart-state')).toHaveCount(0)
    await expect(financial.locator('canvas')).not.toHaveCount(0)
  }
  await financial.getByRole('button',{name:'M5',exact:true}).click();await expect(financial.locator('.financial-chart-state')).toHaveCount(0)
  for(const indicator of ['EXPMA','BOLL','ENE','BBI'])await financial.getByRole('button',{name:indicator,exact:true}).click()
  await expect(financial.locator('.indicator-legend')).toContainText('EXPMA50');await expect(financial.locator('.indicator-legend')).toContainText('BOLL UP');await expect(financial.locator('.indicator-legend')).toContainText('ENE MID')
  await financial.getByRole('button',{name:'放大走势图'}).click();const start=Number(await range.getAttribute('data-start'))
  await financial.getByRole('button',{name:'走势图向左平移'}).click();await expect.poll(async()=>Number(await range.getAttribute('data-start'))).toBeLessThan(start)
  const canvas=financial.locator('.financial-canvas');await canvas.focus();const beforeKeys=Number(await range.getAttribute('data-start'));await canvas.press('ArrowRight');await expect.poll(async()=>Number(await range.getAttribute('data-start'))).toBeGreaterThan(beforeKeys)
  await financial.getByRole('button',{name:'全屏走势图'}).click();const fullscreen=page.getByRole('dialog',{name:'茗喵全屏走势图'})
  await expect(fullscreen).toBeVisible();expect(await fullscreen.boundingBox()).toMatchObject({x:0,y:0,width:1600,height:1080});await expect(fullscreen.locator('canvas')).not.toHaveCount(0)
  const fullscreenCanvas=fullscreen.locator('.financial-canvas'),area=(await fullscreenCanvas.boundingBox())!
  const fullRange=fullscreen.getByLabel('图表可视范围'),beforeWheel=Number(await fullRange.getAttribute('data-end'))-Number(await fullRange.getAttribute('data-start'))
  await page.mouse.move(area.x+area.width*.5,area.y+area.height*.4);await page.mouse.wheel(0,-100)
  await expect.poll(async()=>Number(await fullRange.getAttribute('data-end'))-Number(await fullRange.getAttribute('data-start'))).toBeLessThan(beforeWheel)
  const beforeDrag=Number(await fullRange.getAttribute('data-start'));await page.mouse.move(area.x+area.width*.5,area.y+area.height*.4);await page.mouse.down();await page.mouse.move(area.x+area.width*.65,area.y+area.height*.4,{steps:8});await page.mouse.up();await expect.poll(async()=>Number(await fullRange.getAttribute('data-start'))).not.toBe(beforeDrag)
  await page.screenshot({path:'test-results/native-financial-fullscreen.png',fullPage:true});await page.keyboard.press('Escape');await expect(fullscreen).not.toBeVisible()
  await financial.getByRole('button',{name:'重置走势图'}).click();await page.evaluate(()=>{document.getElementById('main-content')!.scrollTop=0});await page.screenshot({path:'test-results/native-stock-detail-desktop.png',fullPage:true})
  await terminal.getByRole('button',{name:'返回市场',exact:true}).click()
  const ticket=terminal.locator('.ticket');await ticket.getByLabel('委托数量').fill('10')
  await expect(ticket.getByRole('button',{name:'提交买入委托'})).toBeEnabled();await ticket.getByRole('button',{name:'提交买入委托'}).click()
  await terminal.getByRole('dialog').getByRole('button',{name:'确认提交'}).click();await expect(terminal.getByRole('status')).toContainText('成交价')
  await terminal.getByRole('button',{name:'查看证券详情'}).click();await expect(terminal.locator('.execution-panel tbody')).toContainText(username);await terminal.getByRole('button',{name:'返回市场',exact:true}).click()
  await terminal.getByRole('button',{name:'我的持仓',exact:true}).click();await expect(terminal.locator('tbody')).toContainText('茗喵')
  await terminal.getByRole('button',{name:'市场总览',exact:true}).click();await ticket.getByLabel('杠杆倍数').selectOption('2');await ticket.getByLabel('委托数量').fill('10000')
  await expect(ticket.locator('.ticket-calc')).toContainText('13,400,000.00');await expect(ticket.locator('.leverage-warning')).toContainText('30%')
  await ticket.getByRole('button',{name:'提交买入委托'}).click();await expect(terminal.getByRole('dialog')).toContainText('2 倍');await terminal.getByRole('dialog').getByRole('button',{name:'确认提交'}).click();await expect(terminal.getByRole('status')).toContainText('成交价')
  await terminal.getByRole('button',{name:'我的持仓',exact:true}).click();await expect(terminal.locator('dl>div').filter({hasText:'融资借款余额'})).toContainText('13,400,000.00')
  await terminal.getByRole('button',{name:'市场总览',exact:true}).click();await ticket.getByRole('button',{name:'卖出',exact:true}).click();await ticket.getByLabel('委托数量').fill('5005');await expect(ticket.locator('.ticket-calc')).toContainText('6,700,000.00')
  await ticket.getByRole('button',{name:'提交卖出委托'}).click();await terminal.getByRole('dialog').getByRole('button',{name:'确认提交'}).click();await expect(terminal.getByRole('status')).toContainText('成交价')
  await terminal.getByRole('button',{name:'我的持仓',exact:true}).click();await expect(terminal.locator('dl>div').filter({hasText:'融资借款余额'})).toContainText('6,700,000.00')
  await terminal.getByRole('button',{name:'市场总览',exact:true}).click();await ticket.getByLabel('委托方式').selectOption('limit');await ticket.getByLabel('委托价格').fill('1')
  await ticket.getByRole('button',{name:'提交买入委托'}).click();await terminal.getByRole('dialog').getByRole('button',{name:'确认提交'}).click()
  await expect(terminal.getByRole('button',{name:'撤单'})).toBeVisible();await terminal.getByRole('button',{name:'撤单'}).click();await expect(terminal.getByRole('status')).toContainText('已撤销')
  await terminal.getByRole('button',{name:'新手学院',exact:true}).click();await terminal.getByRole('button',{name:/名词词典/}).click();await terminal.getByLabel('搜索交易名词').fill('IMR');await terminal.getByText('IMR / 初始保证金率',{exact:true}).click();await expect(terminal.getByText(/50% IMR 时/)).toBeVisible()
  await terminal.getByRole('button',{name:'市场总览',exact:true}).click();await ticket.getByLabel('杠杆倍数').selectOption('2');await page.evaluate(()=>{document.getElementById('main-content')!.scrollTop=0});await page.screenshot({path:'test-results/native-desktop-market.png',fullPage:true})
  await page.setViewportSize({width:390,height:844});await page.mouse.move(389,840);await page.evaluate(()=>{document.querySelectorAll('#main-content, main, .content, .scroll-area').forEach(el=>{el.scrollTop=0});window.scrollTo(0,0)});await expect(terminal.getByRole('heading',{name:'每一份行动力，都有价值。'})).toBeVisible()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();const mobile=await page.locator('.stock-exchange-shell').boundingBox();expect(mobile).toMatchObject({x:0,y:0,width:390,height:844});await page.screenshot({path:'test-results/native-mobile-market.png',fullPage:true})
  await terminal.getByRole('button',{name:'查看证券详情'}).click();await expect(terminal.locator('.stock-detail-page')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();await page.evaluate(()=>{document.getElementById('main-content')!.scrollTop=0});await page.screenshot({path:'test-results/native-stock-detail-mobile.png',fullPage:true})
  await financial.getByRole('button',{name:'全屏走势图'}).click();await expect(fullscreen).toBeVisible();expect(await fullscreen.boundingBox()).toMatchObject({x:0,y:0,width:390,height:844});await page.screenshot({path:'test-results/native-financial-fullscreen-mobile.png',fullPage:true});await fullscreen.getByRole('button',{name:'退出图表全屏'}).click();await terminal.getByRole('button',{name:'返回市场',exact:true}).click()
  await back.click();await expect(page).toHaveURL(/#\/i\/demo-main\/overview$/);await expect(settings).toBeVisible()
  await page.setViewportSize({width:1600,height:1080});await enter.click();await expect(terminal.locator('.user-name')).toContainText(username);await expect(terminal.getByRole('dialog')).toHaveCount(0)
  await page.goto('/#/i/demo-alt/stock-exchange')
  await terminal.getByRole('button',{name:'已有账户登录'}).click();const wrong=terminal.getByRole('dialog')
  await assertCaptchaCentered(page);await wrong.getByLabel('唯一用户名').fill(username);await wrong.getByLabel('密码',{exact:true}).fill('strong-test-password');await completeCaptcha(page);await wrong.getByRole('button',{name:'验证并登录',exact:true}).click()
  await expect(wrong.getByRole('alert')).toContainText('永久绑定其他 AzurPilot 实例',{timeout:20000})
  await wrong.getByLabel('唯一用户名').fill('海风指挥官');await wrong.getByLabel('密码',{exact:true}).fill('mock-player-password');await completeCaptcha(page);await expect(wrong.getByRole('button',{name:'验证并登录',exact:true})).toBeEnabled();await wrong.getByRole('button',{name:'验证并登录',exact:true}).click();await expect(wrong).not.toBeVisible({timeout:20000})
  await expect(terminal.locator('.user-name')).toContainText('海风指挥官')
  await terminal.getByRole('button',{name:'查看我的身份识别码'}).click();await expect(identityCard.locator('code')).not.toHaveText(identityCode!);await identityCard.getByRole('button',{name:'关闭身份信息'}).click()
  await page.goto('/#/i/demo-main/stock-exchange');await expect(terminal.locator('.user-name')).toContainText(username)
  await terminal.getByRole('button',{name:'查看我的身份识别码'}).click();await expect(identityCard.locator('code')).toHaveText(identityCode!);await identityCard.getByRole('button',{name:'关闭身份信息'}).click()
  const admin=await page.request.post('http://127.0.0.1:8088/api/console/login',{data:{password:'mock-admin-password',recaptchaToken:'recaptcha-test-token'}});expect(admin.ok()).toBeTruthy();const adminToken=(await admin.json()).token
  const ownStock=(await (await page.request.get('http://127.0.0.1:8088/api/market')).json()).stocks.find((s:{username:string})=>s.username===username),renamed=`改名玩家${Date.now()}`
  const edit=await page.request.put(`http://127.0.0.1:8088/api/console/players/${ownStock.id}`,{headers:{Authorization:`Bearer ${adminToken}`},data:{username:renamed,password:'renamed-player-password'}});expect(edit.ok()).toBeTruthy();expect((await edit.json()).player.identityCode).toBe(identityCode)
  await page.reload();const relogin=terminal.getByRole('dialog',{name:'登录交易账户'});await expect(relogin).toBeVisible({timeout:20000});await expect(relogin.getByLabel('唯一用户名')).toBeEditable()
  await relogin.getByLabel('唯一用户名').fill(renamed);await relogin.getByLabel('密码',{exact:true}).fill('renamed-player-password');await completeCaptcha(page);await relogin.getByRole('button',{name:'验证并登录',exact:true}).click();await expect(relogin).not.toBeVisible({timeout:20000})
  await expect(terminal.locator('.user-name')).toContainText(renamed);await terminal.getByRole('button',{name:'查看我的身份识别码'}).click();await expect(identityCard.locator('code')).toHaveText(identityCode!);await identityCard.getByRole('button',{name:'关闭身份信息'}).click()
  expect(responses.some(s=>s.includes('"uploadToken"')||s.includes('"privateKey"'))).toBeFalsy()
  expect(responses.some(s=>/"token":"(?!instance-session)/.test(s))).toBeFalsy();expect(errors).toEqual([])
})

async function assertTopbarPinned(page:import('@playwright/test').Page){
  const topbar=page.locator('.mmex-topbar'),back=topbar.getByRole('link',{name:'返回总览',exact:true}),user=topbar.getByRole('button',{name:'查看我的身份识别码'})
  await page.locator('#main-content').evaluate(el=>{el.scrollTop=0})
  const before=(await topbar.boundingBox())!,a=(await back.boundingBox())!,b=(await user.boundingBox())!
  expect(before.y).toBe(0);expect(a.x+a.width).toBeLessThanOrEqual(b.x)
  expect(Math.abs(a.y+a.height/2-b.y-b.height/2)).toBeLessThan(2)
  await page.locator('#main-content').evaluate(el=>{el.scrollTop=500})
  expect(await page.locator('#main-content').evaluate(el=>el.scrollTop)).toBeGreaterThan(0)
  expect((await topbar.boundingBox())!.y).toBe(0)
  await expect(back).toBeVisible();await expect(user).toBeVisible()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy()
  await page.locator('#main-content').evaluate(el=>{el.scrollTop=0})
}

async function assertCaptchaCentered(page:import('@playwright/test').Page){
  const container=page.locator('.captcha-widget'),widget=container.locator(':scope > div').first()
  await expect.poll(async()=>(await widget.boundingBox())?.width??0).toBeGreaterThanOrEqual(299);await widget.scrollIntoViewIfNeeded();const a=await container.boundingBox(),b=await widget.boundingBox()
  expect(b!.width).toBeGreaterThanOrEqual(299);expect(Math.abs(a!.x+a!.width/2-b!.x-b!.width/2)).toBeLessThan(2)
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy()
}
