from dev_tools.utils import LuaLoader
from module.base.utils import location2node
from module.logger import logger  # Change folder automatically
from module.os.map_data import DIC_OS_MAP


class OSChapter:
    """大型作战（Operation Siren）海域地图数据提取器。

    从游戏 Lua 脚本中提取各海域章节的多语言名称、危险等级、地图尺寸、区域坐标与所属大区等属性。

    Attributes:
        chapter (dict[int, dict]): 海域编号映射的地图元数据字典。
    """

    def __init__(self):
        """初始化提取器并从 Lua 脚本中解析整合各海域数据。"""
        self.chapter = {}
        data = LOADER.load('sharecfg/world_chapter_random.lua')
        for index, chapter in data.items():
            if not isinstance(index, int) or index >= 200:
                continue
            self.chapter[index] = {'cn': chapter['name'], 'hazard_level': chapter['hazard_level']}

        for index, name in self.extract_chapter_name('zh-CN').items():
            self.chapter[index]['cn'] = name
        for index, name in self.extract_chapter_name('en-US').items():
            self.chapter[index]['en'] = name
        for index, name in self.extract_chapter_name('ja-JP').items():
            self.chapter[index]['jp'] = name
        for index, name in self.extract_chapter_name('zh-TW').items():
            self.chapter[index]['tw'] = name
        for index, shape in self.extract_map_size().items():
            self.chapter[index]['shape'] = shape
        # hazard_level
        new = {}
        for index, chapter in self.chapter.items():
            new[index] = {
                # world_chapter_template.lua 结构变化，保留旧版地图尺寸兼容
                'shape': chapter.get('shape', DIC_OS_MAP[index]['shape']),
                'hazard_level': chapter['hazard_level'],
                'cn': chapter['cn'],
                'en': chapter['en'],
                'jp': chapter['jp'],
                'tw': chapter['tw'],
            }
        self.chapter = new

        for index, data in self.extract_map_position().items():
            self.chapter[index].update(data)

    def extract_chapter_name(self, server):
        """提取指定服务器语言下的海域章节名称。

        Args:
            server (str): 服务器标识（如 'zh-CN', 'en-US', 'ja-JP', 'zh-TW'）。

        Returns:
            dict[int, str]: 海域编号到章节名称的映射字典。
        """
        LOADER.server = server
        data = LOADER.load('sharecfg/world_chapter_random.lua')
        out = {}
        for index, chapter in data.items():
            if not isinstance(index, int) or index >= 200:
                continue
            name = chapter['name']
            name = name.replace('é', 'e')  # OCR 无法识别字符 "é"
            out[index] = name

        # 区域 40000 对应海域 154
        for index, chapter in data.items():
            if index == 40000:
                print(server, chapter['name'])
                out[154] = chapter['name']

        return out

    def extract_map_size(self, server='zh-CN'):
        """提取海域地图的网格跨度尺寸。

        Args:
            server (str): 服务器语言标识，默认为 'zh-CN'。

        Returns:
            dict[int, str]: 海域编号到地图尺寸节点表示（如 'I9'）的映射字典。
        """
        LOADER.server = server
        data = LOADER.load('sharecfgdata/world_chapter_template.lua')
        out = {}
        for full_index, chapter in data.items():
            if not full_index // 1000000 == 1 or not chapter['map_sight']:
                continue
            index = (full_index % 1000000) // 1000
            if index < 10:
                index -= 1
            shape = self.parse_map_data(chapter['grids'])
            out[index] = location2node(shape)

        return out

    def parse_map_data(self, grids):
        """计算地图网格的最大长宽跨度。

        Args:
            grids (dict): 网格字典。

        Returns:
            tuple[int, int]: (宽度跨度, 高度跨度)。
        """
        y = [grid[0] for grid in grids.values()]
        x = [grid[1] for grid in grids.values()]
        return (max(x) - min(x), max(y) - min(y))

    def extract_map_position(self, server='zh-CN'):
        """从颜色遮罩配置中提取海域在大地图上的显示位置与区域信息。

        Args:
            server (str): 服务器语言标识，默认为 'zh-CN'。

        Returns:
            dict[int, dict]: 海域编号映射的包含 area_pos、offset_pos 和 region 的字典。
        """
        LOADER.server = server
        data = LOADER.load('sharecfg/world_chapter_colormask.lua')
        out = {}
        for chapter in data.values():
            if 'serial_number' not in chapter:
                continue
            else:
                index = int(chapter['serial_number'])
                if index < 10:
                    index -= 1
                out[index] = {}

            area = chapter['area_pos']
            out[index]['area_pos'] = (area[0], area[1])
            offset = chapter['offset_pos']
            out[index]['offset_pos'] = (offset[0], offset[1])
            out[index]['region'] = chapter['regions']

        return out

    def encode(self):
        """将海域数据格式化为 Python 字典代码行列表。

        Returns:
            list[str]: 格式化后的代码行列表。
        """
        lines = []
        lines.append('# This file was automatically generated by dev_tools/os_extract.py.')
        lines.append("# Don't modify it manually.")
        lines.append('')
        lines.append('DIC_OS_MAP = {')
        for index, chapter in self.chapter.items():
            lines.append(f'    {index}: {str(chapter)},')
        lines.append('}')
        return lines

    def write(self, file):
        """将提取的海域数据写入指定文件。

        Args:
            file (str): 目标输出文件路径。
        """
        print(f'writing {file}')
        with open(file, 'w', encoding='utf-8') as f:
            for text in self.encode():
                f.write(text + '\n')


"""
大型作战地图数据自动化提取工具。

克隆 https://github.com/AzurLaneTools/AzurLaneLuaScripts 获取解密脚本。
参数配置：
    FILE:  解密 Lua 脚本仓库路径，例如 'xxx/AzurLaneLuaScripts'。
    SAVE:  输出保存文件路径，默认为 'module/os/map_data.py'。
"""
FOLDER = ''
SAVE = 'module/os/map_data.py'

LOADER = LuaLoader(FOLDER)
OSChapter().write(SAVE)
