from dev_tools.utils import LuaLoader

FILE_TO_ZONES = {
    11: [44, 84, 125, 95, 104, 52],
    21: [22, 134, 32, 94, 142, 53],
    31: [83, 122, 135, 143, 63, 54],
    32: [23, 62, 114, 51, 41, 14],
    33: [21, 31, 66, 113, 65, 85],
    41: [43, 112, 34, 133, 61, 71],
    51: [81, 132, 123, 105, 91, 64],
    61: [12, 73, 101, 11, 72, 106],
    71: [102, 124, 144, 121, 153, 155],
    81: [24, 92, 111, 25, 82, 42],
    91: [151, 152, 158, 159, 157, 156],
    101: [93, 131, 141, 33, 103, 13]
}
# (code, i) 表示该区域的机密档案编号为 code，且需要前置收集 i 份档案后方可拾取。
ZONE_TO_FILE = {locations[i]: (code, i) for code, locations in FILE_TO_ZONES.items() for i in range(6)}

SAFE = ['Perform', 'Obtain', 'Collect', 'Conduct', 'Use', 'Encounter']
DANGER = ['Gain', 'Defeat', 'Restore', 'Destroy', 'Repel', 'Activate', 'Retrieve']  
# 'Recover' 为档案收集目标。

class OSTarget:
    """大型作战（Operation Siren）海域探索目标提取器。

    Attributes:
        target (dict[int, list]): 海域编号映射的目标判定列表。
    """

    def __init__(self):
        """初始化提取器并从 Lua 数据解析各区域探索目标类型。"""
        self.target = {}
        counter = 0
        for index, desc in DATA.items():
            if not isinstance(index, int) or index // 100 == 154:  # 跳过未实际使用的 154
                continue
            if index % 100 == 1:
                self.target[index // 100] = []
        
        for index, desc in self.extract_target_desc().items():
            target = self.desc_to_target_type(desc)
            if target is None:
                self.target[index // 100].append(ZONE_TO_FILE[index // 100])
            else:
                self.target[index // 100].append(target)

    def extract_target_desc(self):
        """提取各探索目标的描述文本。

        Returns:
            dict[int, str]: 目标 ID 到描述文本的映射字典。
        """
        out = {}
        for index, target in DATA.items():
            if not isinstance(index, int) or index // 100 == 154:  # 跳过未实际使用的 154
                continue
            name = target['target_desc']
            out[index] = name
        
        return out
        
    def desc_to_target_type(self, str):
        """根据目标英文描述的首词判断属于安全海域任务、侵蚀海域任务还是机密档案收集。

        Args:
            str (str): 目标描述文本。

        Returns:
            bool | None: True 表示安全海域任务，False 表示危险/侵蚀海域任务，None 表示档案收集。
        """
        word = str.split()[0]
        if word in SAFE:
            return True
        if word in DANGER:
            return False
        else:  # 为机密档案
            return None
            

    def encode(self):
        """将海域目标数据编码为 Python 代码行列表。

        Returns:
            list[str]: 格式化后的代码行列表。
        """
        lines = []
        lines.append('# This file was automatically generated by dev_tools/os_target_extract.py.')
        lines.append("# Don't modify it manually.")
        lines.append('')
        lines.append('DIC_OS_TARGET = {')
        for index, target in self.target.items():
            lines.append(f'    {index}: {str(target)},')
        lines.append('}')
        return lines

    def write(self, file):
        """将提取的目标数据写入指定文件。

        Args:
            file (str): 目标输出文件路径。
        """
        print(f'writing {file}')
        with open(file, 'w', encoding='utf-8') as f:
            for text in self.encode():
                f.write(text + '\n')

"""
大型作战海域探索目标提取工具。

克隆 https://github.com/AzurLaneTools/AzurLaneLuaScripts 获取解密脚本。
参数配置：
    FILE:  解密 Lua 脚本仓库路径，例如 'xxx/AzurLaneLuaScripts'。
    SAVE:  输出保存文件路径，默认为 'module/os_handler/target_data.py'。
"""
FILE = '../AzurLaneLuaScripts'
SAVE = 'module/os_handler/target_data.py'


LOADER = LuaLoader(FILE, server='EN')
DATA = LOADER.load('./sharecfg/world_target_data.lua')
OSTarget().write(SAVE)