"""舰船升级经验提取工具。

从解密的 Lua 脚本中提取各等级累计升级所需经验，生成供大型作战升级判定使用的数据文件。
"""
from dev_tools.utils import LuaLoader


class ShipEXP:
    """舰船等级经验提取器。

    Attributes:
        ship_exp (list[int]): 各级对应的累计经验列表。
    """

    def __init__(self):
        """初始化提取器并从 Lua 表加载解析经验数据。"""
        self.ship_exp = [0] * 125  # 初始化 0 至 125 级的经验列表
        data = LOADER.load('sharecfg/ship_level.lua')
        total_exp = 0
        for index, exp in data.items():
            if not isinstance(index, int) or index >= 124:
                continue
            total_exp += exp['exp']
            self.ship_exp[exp['level']] = total_exp

    def encode(self):
        """将经验数据转换为生成的 Python 代码行。

        Returns:
            list[str]: 格式化后的 Python 代码行列表。
        """
        lines = []
        lines.append('# This file is auto-generated by dev_tools/ship_exp_extract.py.')
        lines.append('# Do not edit this file manually.')
        lines.append('')
        lines.append('LIST_SHIP_EXP = [')
        for exp in self.ship_exp:
            lines.append(f'    {exp},')
        lines.append(']')
        return lines

    def write(self, file):
        """将生成的经验列表写入目标 Python 文件。

        Args:
            file (str): 目标写入文件路径。
        """
        print(f'writing {file}')
        with open(file, 'w', encoding='utf-8') as f:
            for text in self.encode():
                f.write(text + '\n')


# 舰船升级经验自动提取配置。
# 数据来源：克隆 https://github.com/AzurLaneTools/AzurLaneLuaScripts 获取解密脚本。
# 参数说明：
#     FOLDER: Lua 脚本仓库路径，例如 '../AzurLaneLuaScripts/'
#     SAVE: 输出保存的目标文件路径，如 'module/os/ship_exp_data.py'
FOLDER = '../AzurLaneLuaScripts/'
SAVE = 'module/os/ship_exp_data.py'

if __name__ == '__main__':
    LOADER = LuaLoader(FOLDER)
    ShipEXP().write(SAVE)