import {useCallback,useEffect,useRef,useState} from 'react'
import {ArrowRight,BookOpen,Cat,ChevronDown,Clock3,Coins,LayoutDashboard,ListOrdered,Moon,ShieldCheck,Star,Sun,Trophy,Wallet,WifiOff} from 'lucide-react'
import {OverviewLink} from './OverviewLink'
import {useAPI,useExchange,ApiError,compact,datetime,feesTotal,money,percent,quoteChange} from './api'
import type {Account,ChartPeriod,Market,Meta,Order,Rank,SeasonResult,Stock} from './types'
import {Auth} from './Auth'
import {FinancialChart} from './Charts'
import {Securities} from './Securities'
import {StockDetails} from './StockDetail'
import {shanghaiMonth,useStockDetail} from './useStockDetail'
import {OrdersTable,Portfolio,TradeTicket} from './Trading'
import {Learn} from './Learn'
import {IdentityCard} from './IdentityCard'
import {useStockTheme} from './theme'

const navigation=[{id:'market',label:'市场总览',icon:LayoutDashboard},{id:'portfolio',label:'我的持仓',icon:Wallet},{id:'orders',label:'交易委托',icon:ListOrdered},{id:'leaderboard',label:'资产排行榜',icon:Trophy},{id:'learn',label:'新手学院',icon:BookOpen}]
export function App(){
  const {theme,toggleTheme}=useStockTheme()
  const [showIdentity,setShowIdentity]=useState(false)
  const api=useAPI(),{status}=useExchange(); const snapshot=status.snapshot??undefined
  const [meta,setMeta]=useState<Meta>(),[fatal,setFatal]=useState(''),[market,setMarket]=useState<Market>(),[account,setAccount]=useState<Account>(),[token,setToken]=useState(status.authenticated?'instance-session':''),[page,setPage]=useState('market'),[selected,setSelected]=useState(0),[online,setOnline]=useState(true),[toast,setToast]=useState(''),[bottomTab,setBottomTab]=useState('pending'),[seasons,setSeasons]=useState<SeasonResult[]>([]),[rankingSeason,setRankingSeason]=useState('live'),[watchBusy,setWatchBusy]=useState<number>();const etag=useRef(''),loading=useRef(false),queued=useRef(false),currentToken=useRef(token);currentToken.current=token
  const [period,setPeriod]=useState<ChartPeriod>('time'),[month,setMonth]=useState(shanghaiMonth),[day,setDay]=useState(''),[detailRefresh,setDetailRefresh]=useState(0)
  useEffect(()=>{void api<Meta>('/meta').then(setMeta).catch(e=>setFatal(e.message))},[])
  useEffect(()=>{setToken(status.authenticated?'instance-session':'')},[status.authenticated])
  useEffect(()=>{if(!token){setAccount(undefined);setShowIdentity(false)}},[token])
  const refresh=useCallback(async()=>{queued.current=true;if(loading.current)return;loading.current=true;do{queued.current=false;try{
    const response=await api.response<Market>('/market',etag.current);if(response.status!==304){etag.current=response.etag;setMarket({...response.data!,serverTime:response.serverTime})}else{setMarket(m=>m?{...m,serverTime:response.serverTime}:m)}
    if(currentToken.current){try{const [account,orders]=await Promise.all([api<Account>('/account',undefined,currentToken.current),api<Order[]>('/orders',undefined,currentToken.current)]);setAccount({...account,player:{...account.player,orders}})}catch(e){if(e instanceof ApiError&&e.status===401){setToken('');setAccount(undefined)}else throw e}}
    setOnline(true)
  }catch{setOnline(false)}}while(queued.current);loading.current=false},[api])
  useEffect(()=>{void refresh();const unsubscribe=api.subscribe(update=>{if(update.online===false)setOnline(false);else void refresh()});const visible=()=>{if(document.visibilityState==='visible')void refresh()};document.addEventListener('visibilitychange',visible);return ()=>{unsubscribe();document.removeEventListener('visibilitychange',visible)}},[api,refresh])
  useEffect(()=>{void refresh()},[token,refresh])
  useEffect(()=>{if(!toast)return;const id=setTimeout(()=>setToast(''),5500);return ()=>clearTimeout(id)},[toast])
  useEffect(()=>{document.getElementById('main-content')?.scrollTo({top:0})},[page])
  const selectedStock=market?.stocks.find(s=>s.id===selected)??market?.stocks.find(s=>!s.delisted&&!s.disabled&&s.id!==account?.player.id)??market?.stocks.find(s=>!s.delisted)??market?.stocks[0]
  const chartState=useStockDetail(selectedStock?.id,period,month,day,detailRefresh,page==='market'||page==='stock')
  const stock=selectedStock
  useEffect(()=>{if(page==='leaderboard')void api<SeasonResult[]>('/seasons').then(setSeasons).catch(()=>setToast('历史赛季暂不可用'))},[page])
  function done(message:string){setToast(message);setDetailRefresh(v=>v+1);void refresh()}
  function authenticate(){setToken('instance-session');setToast('账户已就绪，已与当前 AzurPilot 实例绑定')}
  async function watch(stock:Stock){if(!account||watchBusy!==undefined)return;setWatchBusy(stock.id);try{const selected=!(account.player.watchlist??[]).includes(stock.id);const reply=await api<{watchlist:number[]}>('/watchlist',{stockId:stock.id,selected},token);setAccount(current=>current?{...current,player:{...current.player,watchlist:reply.watchlist}}:current);done(selected?`${stock.username} 已添加到自选股`:`${stock.username} 已从自选股移除`)}catch(error){setToast((error as Error).message)}finally{setWatchBusy(undefined)}}
  const backToOverview=<OverviewLink instance={status.instance}/>
  if(fatal)return <div className="startup"><WifiOff/><h2>交易所暂时无法连接</h2><p>{fatal}</p><button className="primary" onClick={()=>location.reload()}>重试连接</button>{backToOverview}</div>
  if(!meta||!market)return <div className="startup"><Cat size={40}/><h2>茗喵证券交易所</h2><p>{online?'正在连接交易终端…':'暂时无法连接市场'}</p>{!online&&<button className="primary" onClick={()=>void refresh()}>重新连接</button>}{backToOverview}</div>
  const principal=account?.player.initialCash??2000000000
  const totalReturn=account?Math.round((account.equity-principal)/principal*1000000):0,pending=account?.player.orders.filter(o=>o.status==='pending')??[]
  const liveRank=market.rankings.find(r=>r.playerId===account?.player.id);const rankings=rankingSeason==='live'?market.rankings:seasons.find(s=>s.season.id===rankingSeason)?.rankings??[]
  const chart=<FinancialChart detail={chartState.detail} period={period} month={month} day={day} onPeriod={setPeriod} onMonth={value=>{setMonth(value);setDay('')}} onDay={setDay} loading={chartState.loading} error={chartState.error} large={page==='stock'}/>
  return <div className="exchange"><aside className="mmex-sidebar"><a className="brand" href="#" onClick={e=>{e.preventDefault();setPage("market")}}><span className="brand-icon"><Cat size={25}/></span><div><strong>茗喵证券交易所</strong><small>MEOWMING EXCHANGE</small></div></a><div className="mmex-sidebar-label">交易工作台</div><nav>{navigation.map(n=><button key={n.id} className={page===n.id?'active':''} onClick={()=>setPage(n.id)}><n.icon size={18}/>{n.label}{n.id==='orders'&&pending.length>0&&<span className="nav-count">{pending.length}</span>}</button>)}</nav><div className="mmex-sidebar-bottom"><section className="season-card"><span className="eyebrow">MONTHLY SEASON</span><strong>{market.season.id} 月赛</strong><span>5 日开赛 · 倒数第 5 日截止</span><div className="season-progress"><i style={{width:`${Math.min(100,Math.max(0,(market.serverTime-market.season.startsAt)/(market.season.endsAt-market.season.startsAt)*100))}%`}}/></div><small>{market.season.settled?'本赛季已结算':market.serverTime<market.season.startsAt?'等待开赛':`距离截止 ${Math.max(0,Math.ceil((market.season.endsAt-market.serverTime)/86400))} 天`}</small></section><span className="mmex-sidebar-disclaimer">模拟证券游戏 · 不涉及真实资金</span></div></aside>
    <div className="mmex-workspace"><header className="mmex-topbar"><div className="mmex-topbar-right">{meta.mock&&<span className="mock-badge">MOCK</span>}{backToOverview}<div className="user-avatar">{account?.player.username.slice(0,1)??'喵'}</div>{token&&account?<button className="user-name identity-trigger" aria-label="查看我的身份识别码" onClick={()=>setShowIdentity(true)}><span>{account.player.username}</span><ChevronDown size={13}/></button>:<span className="user-name">等待开户</span>}<button className="theme-toggle" aria-label={theme==='dark'?'切换到亮色主题':'切换到暗色主题'} title={theme==='dark'?'切换到亮色主题':'切换到暗色主题'} aria-pressed={theme==='light'} onClick={toggleTheme}>{theme==='dark'?<Sun size={16}/>:<Moon size={16}/>}</button></div></header>
      <div className="market-ticker">{market.stocks.filter(s=>!s.delisted).map(s=>{const change=quoteChange(s.quote.price,s.open);return <button key={s.id} onClick={()=>{setSelected(s.id);setPage('market')}}><span>{s.symbol}</span><b>{s.username}</b><strong>{money(s.quote.price)}</strong><span className={change>=0?'rise':'fall'}>{s.open>0?percent(change):'—'}</span></button>})}</div>
      <main>{!online&&<div className="error-banner">行情连接中断，画面保留上次数据。提交委托前请重新连接。<button onClick={()=>void refresh()}>重试</button></div>}
        <div className="account-strip"><section><span>账户总资产 <small>模拟币</small></span><strong>{money(account?.equity??meta.initialCash)}</strong><small className={totalReturn>=0?'rise':'fall'}>{percent(totalReturn)} <span className="muted">本赛季收益</span></small></section><section><span>可用资金</span><strong>{compact(account?.available??meta.initialCash)}</strong><small>现金 {compact(account?.player.cash??meta.initialCash)}</small></section><section><span>冻结与保证金</span><strong>{compact(account?.frozen??0)}</strong><small>持仓保证金 {compact(account?.initialMargin??0)} · 待交收 {compact(account?.unsettled??0)}</small></section><section><span>赛季排名</span><strong>{liveRank?`# ${liveRank.rank}`:'—'} <small>/ {market.participants}</small></strong><small>按净资产实时估值</small></section><section className="exchange-income"><span><Coins size={13}/>交易所本赛季收入</span><strong>{compact(feesTotal(market.season.revenue))}</strong><small>佣金、税费、借券费及融资利息</small></section></div>
        {page==='market'&&<><div className="mmex-section-heading"><div><p className="eyebrow">MARKET OVERVIEW</p><h1>每一份行动力，都有价值。</h1><p className="muted">发现港区中的每一支股票，构建你的投资组合。</p></div><span className={`market-status ${market.open?'open':''}`}><i/>{market.reason}<span>· {market.rules.name}</span></span></div>
          <div className="market-grid"><Securities market={market} account={account} selected={stock?.id} onSelect={setSelected} onWatch={stock=>void watch(stock)} busy={watchBusy}/>
          <div className="market-center">{stock?<><section className="panel quote-panel"><div className="quote-heading"><div><span className="eyebrow">{stock.symbol} <span className="tag">行动力股</span></span><h2>{stock.username}{stock.id===account?.player.id&&<small>我的股票</small>}</h2></div><div className="quote-heading-actions"><button className="watch-button" aria-label={(account?.player.watchlist??[]).includes(stock.id)?"移除当前证券自选":"添加当前证券自选"} aria-pressed={(account?.player.watchlist??[]).includes(stock.id)} disabled={!account||watchBusy!==undefined} onClick={()=>void watch(stock)}><Star size={17} fill={(account?.player.watchlist??[]).includes(stock.id)?"currentColor":"none"}/></button><span className="quote-status"><Clock3 size={13}/>{stock.delisted?'本月已退市':stock.disabled?'停牌':stock.stale?'报价过期':'有效报价'}</span><button className="text-button" aria-label="查看证券详情" onClick={()=>setPage('stock')}>证券详情<ArrowRight size={14}/></button></div></div><div className="quote-price"><strong>{money(stock.quote.price)}</strong><span className={stock.quote.price>=stock.open?'rise':'fall'}>{stock.open>0?percent(quoteChange(stock.quote.price,stock.open)):'—'}<small>较今日开盘</small></span></div><div className="quote-metrics"><span>开盘 <b>{stock.open>0?money(stock.open):'—'}</b></span><span>最高 <b>{chartState.detail?.summary.high?money(chartState.detail.summary.high):'—'}</b></span><span>最低 <b>{chartState.detail?.summary.low?money(chartState.detail.summary.low):'—'}</b></span><span>成交量 <b>{(chartState.detail?.summary.volume??0).toLocaleString()} 股</b></span></div>{chart}<div className="chart-footer"><ShieldCheck size={13}/>报价更新时间 {datetime(stock.quote.observedAt)}<span>实时同步</span></div></section>
            <section className="panel market-note"><div className="note-icon"><BookOpen size={19}/></div><div><strong>第一次来到证券市场？</strong><p>买入、卖空、保证金——用六步入门，读懂每一笔交易。</p></div><button className="text-button" onClick={()=>setPage('learn')}>开始学习<ArrowRight size={15}/></button></section></>:<div className="panel empty-state">暂时没有上市证券，注册后你的股票将自动上市。</div>}</div>
          {stock&&<TradeTicket stock={stock} market={market} account={online?account:undefined} token={token} onDone={done}/>}
        </div><section className="panel recent-orders"><div className="panel-title"><div className="tabs"><button className={bottomTab==='pending'?'active':''} onClick={()=>setBottomTab('pending')}>当前委托 <small>{pending.length}</small></button><button className={bottomTab==='all'?'active':''} onClick={()=>setBottomTab('all')}>成交与委托记录</button></div><button className="text-button" onClick={()=>setPage('orders')}>查看全部<ArrowRight size={14}/></button></div><OrdersTable orders={account?.player.orders??[]} stocks={market.stocks} token={token} onDone={done} onlyPending={bottomTab==='pending'}/></section></>}
        {page==='stock'&&stock&&<StockDetails stock={stock} market={market} account={online?account:undefined} token={token} detail={chartState.detail} chart={chart} onBack={()=>setPage('market')} onDone={done} updated={chartState.updated} error={chartState.error}/>}
        {page==='portfolio'&&account&&<Portfolio account={account} market={market} onSelect={id=>{setSelected(id);setPage('stock')}}/>}
        {page==='orders'&&<><div className="mmex-section-heading"><div><p className="eyebrow">ORDERS & EXECUTIONS</p><h1>交易委托</h1><p className="muted">挂单按条件触发全量成交；显示完整成交与委托记录。</p></div><span className="tag">{pending.length} 笔待触发</span></div><section className="panel"><OrdersTable orders={account?.player.orders??[]} stocks={market.stocks} token={token} onDone={done}/></section></>}
        {page==='leaderboard'&&<><div className="mmex-section-heading"><div><p className="eyebrow">SEASON LEADERBOARD</p><h1>港区资产榜</h1><p className="muted">资产采用最新报价估值，借券费用计入净值，行情与排名实时同步。</p></div><select aria-label="排行榜赛季" value={rankingSeason} onChange={e=>setRankingSeason(e.target.value)}><option value="live">{market.season.id} · 当前赛季</option>{seasons.map(s=><option key={s.season.id} value={s.season.id}>{s.season.id} · 已结算</option>)}</select></div><div className="podium">{rankings.slice(0,3).map(r=><RankCard key={r.playerId} rank={r}/>)}</div><section className="panel"><div className="panel-title"><h3>全部玩家</h3><span className="muted">按净资产降序，平手按上市顺序</span></div><div className="table-scroll"><table><thead><tr><th>排名</th><th>玩家</th><th>总资产 (模拟币)</th><th>赛季收益率</th></tr></thead><tbody>{rankings.map(r=><tr key={r.playerId} className={r.playerId===account?.player.id?'my-rank':''}><td>#{r.rank}</td><td>{r.username}{r.playerId===account?.player.id&&<span className="tag">我</span>}</td><td>{money(r.equity)}</td><td className={r.returnPPM>=0?'rise':'fall'}>{percent(r.returnPPM)}</td></tr>)}</tbody></table></div></section><section className="panel revenue-panel"><Coins size={30}/><div><span>交易所本赛季总收入</span><strong>{money(feesTotal(market.season.revenue))} <small>模拟币</small></strong></div>{Object.entries(market.season.revenue).map(([k,v])=><div key={k}><span>{{commission:'佣金',stamp:'印花税',levy:'交易征费',borrow:'借券费',financing:'融资利息'}[k]}</span><b>{money(v)}</b></div>)}</section></>}
        {page==='learn'&&<Learn rules={market.rules} initialCash={market.initialCash??meta.initialCash} delistThreshold={market.delistThreshold}/>}
      </main><footer className="footer"><span><Cat size={13}/>MMEX · 茗喵证券交易所</span><span>截止 {datetime(market.season.endsAt-1)} · 上海时间</span><span>模拟交易，风险在这里练习。</span></footer>
    </div>{!token&&<Auth meta={{...meta,initialCash:market.initialCash??meta.initialCash}} snapshot={snapshot} onSuccess={authenticate}/>} {toast&&<div className="toast" role="status"><ShieldCheck size={17}/>{toast}</div>}
    {showIdentity&&token&&account&&<IdentityCard player={account.player} onClose={()=>setShowIdentity(false)}/>}
  </div>
}
function RankCard({rank}:{rank:Rank}){return <section className={`panel rank-card rank-${rank.rank}`}><Trophy size={23}/><span>NO. 0{rank.rank}</span><h2>{rank.username}</h2><strong>{compact(rank.equity)} <small>模拟币</small></strong><span className={rank.returnPPM>=0?'rise':'fall'}>{percent(rank.returnPPM)}</span></section>}
