import {useState,type ReactNode} from 'react'
import {ArrowLeft,ArrowUpRight,Clock3,Radio} from 'lucide-react'
import type {Account,Market,Stock,StockDetail as Detail} from './types'
import {compact,datetime,money,percent,quoteChange,sideName} from './api'
import {TradeTicket} from './Trading'

const units=(n:number)=>n>=100000000?`${(n/100000000).toFixed(2)}亿`:n>=10000?`${(n/10000).toFixed(2)}万`:n.toLocaleString('zh-CN')
const tradeTime=(t:number)=>new Date(t).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false})
export function StockDetails({stock,market,account,token,detail,chart,onBack,onDone,updated,error}:{stock:Stock;market:Market;account?:Account;token:string;detail?:Detail;chart:ReactNode;onBack:()=>void;onDone:(m:string)=>void;updated:number;error:string}){
  const [tab,setTab]=useState<'prints'|'pending'>('prints')
  const summary=detail?.summary,change=quoteChange(stock.quote.price,stock.open),buy=summary?.buyVolume??0,sell=summary?.sellVolume??0,total=buy+sell
  return <div className="stock-detail-page">
    <div className="stock-detail-nav"><button className="text-button" onClick={onBack}><ArrowLeft size={14}/>返回市场</button><span>证券详情 / {stock.symbol}</span><span className={error?'fall':'muted'}><Radio size={12}/>{error?'行情重连中':'实时同步'}{updated?` · ${new Date(updated*1000).toLocaleTimeString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false})}`:''}</span></div>
    <section className="panel stock-detail-quote"><div className="stock-detail-identity"><span className="eyebrow">{stock.symbol} · ACTION POINT EQUITY</span><h1>{stock.username}<span className="tag">行动力股</span></h1><span className="quote-status"><Clock3 size={12}/>{stock.delisted?'本月已退市':stock.disabled?'停牌':stock.stale?'报价过期':'交易中'} · {market.rules.name}</span></div><div className={`stock-detail-price ${change>=0?'rise':'fall'}`}><strong>{money(stock.quote.price)}</strong><span>{stock.open>0?percent(change):'—'} <small>较今日开盘</small></span></div><dl className="stock-detail-metrics"><div><dt>今开</dt><dd>{stock.open>0?money(stock.open):'—'}</dd></div><div><dt>最高</dt><dd className="rise">{summary?.high?money(summary.high):'—'}</dd></div><div><dt>最低</dt><dd className="fall">{summary?.low?money(summary.low):'—'}</dd></div><div><dt>昨收</dt><dd>{summary?.previousClose?money(summary.previousClose):'—'}</dd></div><div><dt>成交量 / 股</dt><dd>{units(summary?.volume??0)}</dd></div><div><dt>成交额 / 模拟币</dt><dd>{compact(summary?.turnover??0)}</dd></div></dl></section>
    <div className="stock-detail-grid"><div className="stock-detail-main"><section className="panel stock-detail-chart">{chart}</section><section className="panel execution-panel"><div className="panel-title"><div className="tabs"><button className={tab==='prints'?'active':''} onClick={()=>setTab('prints')}>逐笔成交 <small>{detail?.trades.length??0}</small></button><button className={tab==='pending'?'active':''} onClick={()=>setTab('pending')}>实时挂单 <small>{detail?.pending.length??0}</small></button></div><span className="muted">{tab==='prints'?'所选月份完整成交记录':'全部待触发委托'}</span></div><div className="table-scroll"><table><thead>{tab==='prints'?<tr><th>时间 · 上海</th><th>成交价</th><th>数量 / 股</th><th>方向</th><th>成交额</th><th>玩家</th><th>成交方式</th></tr>:<tr><th>提交时间 · 上海</th><th>委托 / 触发价</th><th>数量 / 股</th><th>方向</th><th>玩家</th><th>委托方式</th><th>有效期</th></tr>}</thead><tbody>{tab==='prints'?detail?.trades.map(t=><tr key={t.id}><td>{tradeTime(t.time)}</td><td className={['buy','cover'].includes(t.side)?'rise':'fall'}>{money(t.price)}</td><td>{t.quantity.toLocaleString()}</td><td className={['buy','cover'].includes(t.side)?'rise':'fall'}>{sideName[t.side]}</td><td>{money(t.price*t.quantity)}</td><td>{t.username}</td><td>{t.forced?'强制平仓':t.kind==='limit'?'限价成交':'市价成交'}</td></tr>):detail?.pending.map(o=><tr key={o.id}><td>{datetime(o.createdAt)}</td><td>{money(o.limit)}</td><td>{o.quantity.toLocaleString()}</td><td className={['buy','cover'].includes(o.side)?'rise':'fall'}>{sideName[o.side]}</td><td>{o.username}</td><td>{o.kind==='stop'?'止损触发':'限价委托'}</td><td>{o.tif==='DAY'?'当日有效':'撤销前有效'}</td></tr>)}</tbody></table>{!(tab==='prints'?detail?.trades.length:detail?.pending.length)&&<div className="empty-state">{tab==='prints'?'暂无成交，成交记录会自动出现在这里。':'暂无待触发限价委托。'}</div>}</div><div className="execution-note"><ArrowUpRight size={13}/>游戏采用无限模拟流动性，挂单满足条件即按行动力报价全量成交。成交不会改变股票报价。</div></section></div>
      <aside className="stock-detail-aside"><TradeTicket stock={stock} market={market} account={account} token={token} onDone={onDone}/><section className="panel detail-flow"><div className="panel-title"><h3>成交方向分布</h3><small className="muted">{summary?.day??'本日'}</small></div><div className="flow-values"><span className="rise">买入 / 回补<b>{units(buy)} 股</b></span><span className="fall">卖出 / 卖空<b>{units(sell)} 股</b></span></div><div className="flow-bar"><i style={{width:`${total?buy/total*100:50}%`}}/></div><p className="muted">按主动交易方向统计实际游戏成交；成交量含系统强制平仓，每笔委托计一次。</p></section><section className="panel detail-source"><h3>证券资料</h3><dl><div><dt>报价来源</dt><dd>玩家实例行动力记录</dd></div><div><dt>报价更新时间</dt><dd>{datetime(stock.quote.observedAt)}</dd></div><div><dt>每手股数</dt><dd>{market.rules.lotSize} 股</dd></div><div><dt>交易价格</dt><dd>1 行动力 = 1 模拟币</dd></div></dl><p className="muted">K 线按已采集记录计算开、高、低、收，缺失时段不填造数据。交易量来自交易所账本。</p></section></aside>
    </div>
  </div>
}
