export interface Fees {commission:number;stamp:number;levy:number;borrow:number;financing?:number}
export interface Rules {id:string;name:string;description:string;commissionPPM:number;minCommission:number;stampPPM:number;stampSide:string;stampRound:number;levyPPM:number;borrowAnnualPPM:number;financingAnnualPPM:number;imrPPM:number;mmrPPM:number;lotSize:number;sellDelayDays:number;cashDelayDays:number;timezone:string;sessions:string[];weekdaysOnly:boolean;holidays:string[];quoteTTLSeconds:number;source:string}
export interface Settings {initialCash:number;delistThreshold:number;active:Rules;presets:Rules[];startDay:number;endDaysFromLast:number;paused:boolean}
export interface Quote {price:number;previous:number;observedAt:number;uploadedAt:number}
export interface Stock {id:number;symbol:string;username:string;quote:Quote;stale:boolean;disabled:boolean;delisted:boolean;open:number}
export interface Season {id:string;startsAt:number;endsAt:number;settled:boolean;revenue:Fees}
export interface Rank {rank:number;playerId:number;username:string;equity:number;returnPPM:number}
export interface Market {initialCash?:number;delistThreshold:number;revision:number;serverTime:number;season:Season;rules:Rules;open:boolean;reason:string;stocks:Stock[];rankings:Rank[];lifetimeRevenue:Fees;participants:number}
export interface Position {stockId:number;quantity:number;cost:number;lots:{quantity:number;availableAt:number}[];borrowAt:number;loan?:number;marginPPM?:number;financingAt?:number}
export interface Order {id:number;clientId:string;stockId:number;side:string;kind:string;tif:string;quantity:number;limit:number;leverage?:number;status:string;price:number;fees:Fees;createdAt:number;executedAt:number;reason:string;reserved:number;rules:Rules}
export interface Player {id:number;username:string;identityCode:string;joinedAt:number;cash:number;initialCash?:number;quote:Quote;positions:Record<string,Position>;orders:Order[];realized:number;fees:Fees;disabled:boolean;delisted:boolean;watchlist?:number[]}
export interface Account {player:Player;equity:number;available:number;frozen:number;shortLiability:number;initialMargin:number;maintenanceMargin:number;unsettled:number;borrowAccrued:number;financingDebt?:number;financingAccrued?:number;longMargin?:number}
export interface Meta {name:string;domain:string;mock:boolean;allowedOrigins:string[];initialCash:number;noticeVersion:string}
export interface QuotePoint {time:number;price:number}
export interface SeasonResult {season:Season;rankings:Rank[]}
export interface Snapshot {actionPoints:number;observedAt:number;instance:string}
export type ChartPeriod='time'|'day'|'m5'|'m10'|'m20'|'m30'|'m60'
export interface Candle {time:number;open:number;high:number;low:number;close:number;samples:number;volume:number;turnover:number;buyVolume:number;sellVolume:number}
export interface TradePrint {id:number;stockId:number;username:string;side:string;kind:string;quantity:number;price:number;time:number;forced:boolean}
export interface PublicPending {id:number;username:string;side:string;quantity:number;limit:number;createdAt:number;tif:string;kind:string}
export interface StockDetail {stock:Stock;period:ChartPeriod;month:string;day:string;displayFrom:number;bars:Candle[];trades:TradePrint[];pending:PublicPending[];summary:{day:string;open:number;high:number;low:number;previousClose:number;volume:number;turnover:number;buyVolume:number;sellVolume:number};coverage:{count:number;firstObservedAt:number;lastObservedAt:number;reconciledAt:number}}
