import { expect, test } from '@playwright/test'

test('账号操作按次弹出密码验证，取消不执行且不保存密码', async ({page}, testInfo) => {
  let advertisedTPM = false
  await page.routeWebSocket('**/api/v1/ws', socket => {
    const server = socket.connectToServer()
    server.onMessage(message => {
      const response = JSON.parse(String(message))
      if (response.result && 'tpm_available' in response.result) response.result.tpm_available = advertisedTPM
      socket.send(JSON.stringify(response))
    })
  })
  await page.goto('/#/i/testpilot/task/Alas')
  const panel = page.getByTestId('account-panel')
  const dialog = page.getByRole('dialog')
  const password = 'Browser-Test-Passphrase-81!'
  const replacement = 'Replacement-Browser-Passphrase-93!'
  const authenticate = async (action: string, value: string, confirm = false) => {
    await panel.getByRole('button', {name: action, exact: true}).click()
    await expect(dialog).toBeVisible()
    await expect(dialog.locator('#account-password')).toBeFocused()
    await expect(dialog.locator('#account-password')).toHaveValue('')
    await dialog.locator('#account-password').fill(value)
    if (confirm) await dialog.locator('#account-confirm').fill(value)
    await dialog.getByRole('button', {name: '确认', exact: true}).click()
    await expect(dialog).toHaveCount(0)
  }
  await expect(panel.getByRole('heading', {name: '账号管理', exact: true})).toBeVisible()
  await expect(panel.locator('#account-password')).toHaveCount(0)
  await expect(panel.getByRole('button', {name: '设置实例密码', exact: true})).toBeEnabled()
  await authenticate('设置实例密码', password, true)
  await expect(panel.getByRole('switch')).toHaveAttribute('aria-checked', 'false')
  await expect(panel.getByText('本机密钥自动解锁：安全性低于 TPM', {exact: true})).toBeVisible()
  await authenticate('绑定本机密钥自动解锁', password)
  await expect(panel.getByText('内存已解锁 · 已绑定本机密钥', {exact: true})).toBeVisible()
  await expect(panel.getByRole('button', {name: '绑定本机 TPM 自动解锁', exact: true})).toHaveCount(0)
  advertisedTPM = true
  await page.reload()
  await expect(panel.getByRole('button', {name: '解除本机密钥绑定', exact: true})).toBeVisible()
  await expect(panel.getByRole('button', {name: '绑定本机 TPM 自动解锁', exact: true})).toHaveCount(0)
  advertisedTPM = false
  await panel.getByRole('switch').click()
  await expect(dialog).toBeVisible()
  await dialog.locator('#account-password').fill(password)
  await dialog.getByRole('button', {name: '取消', exact: true}).click()
  await expect(dialog).toHaveCount(0)
  await expect(panel.getByRole('switch')).toHaveAttribute('aria-checked', 'false')
  await panel.getByRole('button', {name: '验证密码并查看账号', exact: true}).click()
  await expect(dialog.locator('#account-password')).toHaveValue('')
  await dialog.locator('#account-password').fill(password)
  await page.keyboard.press('Escape')
  await expect(dialog).toHaveCount(0)
  await expect(panel.getByText('尚无账号快照。请先在游戏中登录，再备份。', {exact: true})).toHaveCount(0)
  await authenticate('验证密码并查看账号', password)
  await expect(panel.getByText('尚无账号快照。请先在游戏中登录，再备份。', {exact: true})).toBeVisible()
  await panel.getByRole('button', {name: '隐藏账号信息', exact: true}).click()
  await expect(panel.getByText('尚无账号快照。请先在游戏中登录，再备份。', {exact: true})).toHaveCount(0)
  expect(await page.evaluate(() => JSON.stringify({local: {...localStorage}, session: {...sessionStorage}}))).not.toContain(password)
  await panel.getByRole('button', {name: '清除内存解锁', exact: true}).click()
  await expect(panel.getByText('内存未解锁 · 已绑定本机密钥', {exact: true})).toBeVisible()
  await panel.getByRole('button', {name: '修改实例密码', exact: true}).click()
  await dialog.locator('#account-password').fill(password)
  await dialog.locator('#account-new-password').fill(replacement)
  await dialog.locator('#account-confirm').fill(replacement)
  await dialog.getByRole('button', {name: '确认', exact: true}).click()
  await expect(dialog).toHaveCount(0)
  await authenticate('验证密码并查看账号', replacement)
  await expect(panel.getByText('尚无账号快照。请先在游戏中登录，再备份。', {exact: true})).toBeVisible()
  await panel.screenshot({path: testInfo.outputPath('account-desktop.png'), animations: 'disabled'})
  await page.setViewportSize({width: 390, height: 844})
  await panel.getByRole('button', {name: '备份当前游戏账号', exact: true}).click()
  await expect(dialog.locator('#account-label')).toBeVisible()
  await expect(dialog).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await dialog.screenshot({path: testInfo.outputPath('account-mobile.png'), animations: 'disabled'})
  await dialog.getByRole('button', {name: '取消', exact: true}).click()
  await authenticate('解除本机密钥绑定', replacement)
  await expect(panel.getByText('本机密钥自动解锁：安全性低于 TPM', {exact: true})).toBeVisible()
  advertisedTPM = true
  await page.reload()
  await expect(panel.getByRole('button', {name: '绑定本机 TPM 自动解锁', exact: true})).toBeVisible()
  await expect(panel.getByRole('button', {name: '绑定本机密钥自动解锁', exact: true})).toHaveCount(0)
  advertisedTPM = false
  await page.reload()
  await expect(panel.getByRole('button', {name: '绑定本机密钥自动解锁', exact: true})).toBeVisible()
  await expect(panel.getByRole('button', {name: '绑定本机 TPM 自动解锁', exact: true})).toHaveCount(0)
})
