import { expect, test } from '@playwright/test'

test.beforeEach(async ({page}) => {
  await page.addInitScript(() => localStorage.setItem('azurpilot.dev-mode', '1'))
  await page.route('https://api.yppp.net/**', route => route.abort())
  await page.goto('/#/dev')
  await expect(page.getByRole('heading', {name: '表单控件', exact: true})).toBeVisible()
})

test('共享表单保留键盘交互、密码切换与原生值类型', async ({page}) => {
  const select = page.getByRole('combobox', {name: '下拉框', exact: true})
  await select.click()
  await page.getByRole('option', {name: 'ADB', exact: true}).click()
  await expect(select).toHaveText('ADB')
  await select.focus()
  await page.keyboard.press('ArrowDown')
  await page.keyboard.press('ArrowDown')
  await page.keyboard.press('Enter')
  await expect(select).toHaveText('Nemulator')
  const toggle = page.getByRole('switch', {name: '开关', exact: true})
  await toggle.focus()
  await page.keyboard.press('Space')
  await expect(toggle).toHaveAttribute('aria-checked', 'false')
  // 实测盒高会带亚像素小数，取整以免测量噪声把尺寸判成不达标。
  expect(Math.round((await toggle.boundingBox())!.height)).toBeGreaterThanOrEqual(44)
  await expect(page.getByRole('switch', {name: '禁用开关'})).toBeDisabled()
  const checkbox = page.getByRole('checkbox', {name: 'Alas', exact: true})
  await checkbox.focus()
  await page.keyboard.press('Space')
  await expect(checkbox).not.toBeChecked()
  await page.getByRole('checkbox', {name: 'Commission', exact: true}).check()
  await expect(page.getByRole('checkbox', {name: 'Opsi', exact: true})).toBeChecked()
  const password = page.locator('#dev-password')
  await password.fill('测试密码-123')
  await page.getByRole('button', {name: '显示密码', exact: true}).click()
  await expect(password).toHaveAttribute('type', 'text')
  await expect(password).toHaveValue('测试密码-123')
  await page.getByRole('button', {name: '隐藏密码', exact: true}).click()
  await expect(password).toHaveAttribute('type', 'password')
  await page.locator('#dev-number').fill('42')
  await expect(page.locator('#dev-number')).toHaveValue('42')
  await page.locator('#dev-datetime').fill('2026-09-16T12:34:56')
  await expect(page.locator('#dev-datetime')).toHaveValue('2026-09-16T12:34:56')
  await expect(page.locator('#dev-invalid')).toHaveAccessibleDescription('请输入有效值，当前输入已保留。')
  await expect(page.locator('#dev-invalid')).toHaveCSS('border-top-color', await page.locator('#dev-invalid-status').evaluate(element => getComputedStyle(element).color))
  await expect(page.locator('#dev-search')).toHaveCSS('border-top-width', '0px')
  await page.locator('#dev-search').focus()
  await expect(page.locator('.input-icon').filter({has: page.locator('#dev-search')})).not.toHaveCSS('box-shadow', 'none')
})

test('表单在浅深主题、移动端和强制颜色模式下保持可用', async ({page}, testInfo) => {
  const section = page.locator('.config-group').filter({has: page.getByRole('heading', {name: '表单控件', exact: true})})
  await section.scrollIntoViewIfNeeded()
  for (const theme of ['light', 'dark']) {
    await page.evaluate(theme => {document.documentElement.dataset.theme = theme}, theme)
    await page.locator('#dev-text').focus()
    await expect(page.locator('#dev-text')).not.toHaveCSS('box-shadow', 'none')
    await section.screenshot({path: testInfo.outputPath(`forms-${theme}.png`)})
  }
  await page.setViewportSize({width: 390, height: 844})
  await expect(page.locator('#dev-select')).toHaveCSS('font-size', '16px')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await section.screenshot({path: testInfo.outputPath('forms-mobile.png'), style: '.topbar, .skip-link {visibility: hidden !important}'} )
  await page.emulateMedia({forcedColors: 'active', reducedMotion: 'reduce'})
  await page.locator('#dev-select').click()
  await expect(page.getByRole('listbox')).toBeVisible()
  await page.keyboard.press('Escape')
  await page.getByRole('checkbox', {name: 'Event', exact: true}).check()
  await expect(page.getByRole('checkbox', {name: 'Event', exact: true})).toBeChecked()
})

test('自绘菜单支持取消、文字查找、主题与移动端边界', async ({page}, testInfo) => {
  const select = page.getByRole('combobox', {name: '下拉框', exact: true})
  await select.click()
  const menu = page.getByRole('listbox')
  await expect(menu).toHaveCSS('border-radius', '13px')
  await expect(page.getByRole('option', {name: 'Auto', exact: true})).toHaveAttribute('aria-selected', 'true')
  await page.keyboard.press('End')
  await page.keyboard.press('Escape')
  await expect(select).toHaveText('Auto')
  await expect(select).toBeFocused()
  await page.keyboard.press('n')
  await page.keyboard.press('Enter')
  await expect(select).toHaveText('Nemulator')
  for (const theme of ['light', 'dark']) {
    await page.evaluate(theme => {document.documentElement.dataset.theme = theme}, theme)
    await select.click()
    await menu.screenshot({path: testInfo.outputPath(`select-${theme}.png`)})
    await page.keyboard.press('Escape')
  }
  await page.setViewportSize({width: 390, height: 844})
  await select.click()
  const bounds = (await menu.boundingBox())!
  expect(bounds.x).toBeGreaterThanOrEqual(0)
  expect(bounds.x + bounds.width).toBeLessThanOrEqual(390)
  expect(bounds.y).toBeGreaterThanOrEqual(0)
  expect(bounds.y + bounds.height).toBeLessThanOrEqual(844)
  await page.keyboard.press('Tab')
  await expect(menu).toHaveCount(0)
  await select.click()
  await page.getByRole('heading', {name: '表单控件', exact: true}).click()
  await expect(menu).toHaveCount(0)
})

test('弹窗内选择配置后能够提交，菜单不会被 dialog 遮挡', async ({page}) => {
  await page.goto('/#/')
  await page.getByRole('button', {name: '新建实例', exact: true}).click()
  const dialog = page.getByRole('dialog')
  const select = dialog.getByRole('combobox', {name: '初始配置', exact: true})
  await select.click()
  await page.getByRole('option', {name: 'testpilot', exact: true}).click()
  await expect(select).toHaveText('testpilot')
  await select.click()
  await page.keyboard.press('Escape')
  await expect(dialog).toBeVisible()
  const name = `select_${Date.now()}`
  await dialog.getByLabel('实例名称').fill(name)
  await dialog.getByRole('button', {name: '创建实例', exact: true}).click()
  await expect(page).toHaveURL(new RegExp(`/i/${name}/overview$`))
})
